### ISSUE TITLE
Workflow Backup

### ISSUE THREAD

**Issue by metbril** [jordanmerrick/workflowdirectory#26]
The workflow creates a Backup.zip file in the Workflow folder instead of a dated archive in the Backup sub folder. 

https://github.com/jordanmerrick/workflowdirectory/tree/master/workflows/Back%20Up%20Workflows%20to%20iCloud

**Comment by jordanmerrick** [comment]
Link to the workflow seems to be missing.

**Comment by metbril** [comment]
I'm not sure what you mean. I have stripped some text from the original issue to make it more clear.

**Comment by jordanmerrick** [comment]
Sorry about that, I thought this was a submission. Thanks for reporting! I've updated the workflow so it should create properly named archives.

The issue appears if the directory /Workflow/Backup doesn't exist in iCloud Drive. Instead of creating the directory, Workflow just names the file "Backup" instead.
